coverage:100%
  status:100%
    project:100%
      default:100%
        tarauto:100%
        threshold:100%
    patch:100%
      default:100%
        informational:false
github_checks:100%
  annotations:true
